CHANGELOG.md, identity-hostdata.gemspec, lib/login_gov/hostdata/ec2.rb, lib/login_gov/hostdata/version.rb
When attempting to discover the region or account ID using the EC2 metadata
service, use fetch to raise KeyError if the instance identity document
doesn't contain the required keys.
These methods should never return nil.
=> Use fetch to improve safety of metadata methods.

identity-hostdata.gemspec, lib/login_gov/hostdata.rb, lib/login_gov/hostdata/version.rb, spec/login_gov/hostdata_spec.rb
I discovered a new "info" file that we were reading manually in the IDP:
https://github.com/18F/identity-idp/blob/master/lib/tasks/check_for_pending_migrations.rake
So let's add a method for it so we can clean up that code!
=> Add helper method to read info/role file (instance role)

lib/login_gov/hostdata.rb, lib/login_gov/hostdata/version.rb
**Why**: So `instance_role` and `env` don't myseriously have the same value after one is set.
=> Fix a bug where `instance_role` was memoized as `@env`

lib/login_gov/hostdata.rb, lib/login_gov/hostdata/version.rb
This function gets used on every page for the banners in the IDP (https://github.com/18F/identity-idp/blob/master/lib/feature_management.rb#L72-L78) and most of the other methods in the module are memoized, so why not do that for `in_datacenter?` to skip some file system effort 🙂
Since the function returns boolean, the usual `||=` syntax doesn't work
=> memoize in_datacenter method

.circleci/config.yml, CHANGELOG.md, lib/login_gov/hostdata.rb, lib/login_gov/hostdata/version.rb, spec/login_gov/hostdata_spec.rb
This will let us access the `idp_run_migrations` config in the IDP which we can use to be smarter about migrations in fresh environments
=> Adds config, parsing of the <ENV>.json file

CHANGELOG.md, lib/identity/hostdata/version.rb, lib/login_gov/hostdata.rb, spec/identity/hostdata_spec.rb
If we don't do this, I am pretty sure that our deploys will break because of this line in the config:
https://github.com/18F/identity-idp-config/blob/d4c0abad42ceae1a6bf95423824e439dbd0e82d0/service_providers.yml#L266-L267
=> Add legacy namespace to smooth transition in config repo

lib/identity/hostdata.rb, lib/identity/hostdata/settings.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/settings_spec.rb, spec/identity/hostdata_spec.rb
Lifted work from https://github.com/18f/identity-idp/pull/4408
Next steps:
- Update the IDP to do a giant `s/AppConfig.env/Identity::Hostdata.settings/g`
- Update PKI, Dashboard
The biggest bummer was that we already have `Identity::Hostdata.config` and `Identity::Hostdata.env`... which are great names for what this does, so I went with settings. Very open to other naming ideas!
=> Add Identity::Hostdata.settings, to store data from config (LG-4247)

CHANGELOG.md, docs/contract.md, lib/identity/hostdata.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata_spec.rb
**Why**: So they can be explicitly configured to still work outside of a chef provisioned environment or AWS environment where we don't have access to EC2 metadata.
=> Allow the hostdata configurations and AWS configurations to be overridden by env vars

CHANGELOG.md, identity-hostdata.gemspec, lib/identity/hostdata.rb, lib/identity/hostdata/config_reader.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_reader_spec.rb
**Why**: So the hostdata gem can manage the footwork involved with downloading configs and parsing them. This will enable us to use the hostdata gem to consume configs in a consistent manner across host types.
=> Add a ConfigReader class

CHANGELOG.md, lib/identity/hostdata/config_reader.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_reader_spec.rb
**Why**: When `Hostdata#instance_role` is invoked on dashboards it returns `app` but the application.yml uses `dashboard` in its path
=> Correct the path component for the dashboard application.yml

CHANGELOG.md, lib/identity/hostdata/config_reader.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_reader_spec.rb
**Why**: Because the configs for migrations live under the `idp` prefix in S3
=> Fix the S3 paths when the instance role is migration

CHANGELOG.md, lib/identity/hostdata/ec2.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_reader_spec.rb, spec/identity/hostdata/ec2_spec.rb, spec/identity/hostdata_spec.rb
Devops issue https://github.com/18F/identity-devops/issues/2948
Use version 2 of ec2 instance metadata service.
=> Update to use v2 instance metadata service

lib/identity/hostdata/s3.rb, lib/identity/hostdata/version.rb
This S3 client is used almost exclusively for reading config data, but seems like it couldn't hurt to disable these anyways
=> Stop AWS S3 from calculating MD5 checksums, not FIPS-supported

lib/identity/hostdata.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata_spec.rb
I noticed the IDP was building these kinds of strings manually in a bunch of different places, seemed like a good opportunity to clean things up a tad, IDP PR to demo this change coming shortly
=> Bucket name helper method

lib/identity/hostdata/config_reader.rb
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
```
Removed methods
The following deprecated methods are removed.
Dir.exists? [[Feature #17391](https://bugs.ruby-lang.org/issues/17391)]
File.exists? [[Feature #17391](https://bugs.ruby-lang.org/issues/17391)]
```
=> Use File.exist? instead of File.exists? which has been removed in Ruby 3.2.0

lib/identity/hostdata/config_reader.rb, lib/identity/hostdata/version.rb
Review applications are in a datacenter, but we don't want to read the remote config (yet at least). This adds an environment variable config that allows skipping reading S3.
Related to https://github.com/18F/identity-idp/pull/8854
=> Allow skipping remote config

lib/identity/hostdata/s3.rb, lib/identity/hostdata/version.rb
We infrequently see failures early in the provisioning process when fetching S3 data with the exception `Aws::Sigv4::Errors::MissingCredentialsError`. This PR adds a few retries to hopefully avoid the exception.
<details>
<summary>Stacktrace</summary>
```
Aws::Errors::MissingCredentialsError: unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)
/bundle/ruby/3.3.0/gems/aws-sdk-core-3.179.0/lib/aws-sdk-core/plugins/sign.rb:115:in `rescue in initialize'
/bundle/ruby/3.3.0/gems/aws-sdk-core-3.179.0/lib/aws-sdk-core/plugins/sign.rb:104:in `initialize'
/bundle/ruby/3.3.0/gems/aws-sdk-core-3.179.0/lib/aws-sdk-core/plugins/sign.rb:30:in `new'
/bundle/ruby/3.3.0/gems/aws-sdk-core-3.179.0/lib/aws-sdk-core/plugins/sign.rb:30:in `signer_for' …
```
=> Retry Instance Profile Credential Retrieval

CHANGELOG.md, README.md, identity-hostdata.gemspec, lib/identity/hostdata.rb, lib/identity/hostdata/config_builder.rb, lib/identity/hostdata/version.rb, lib/login_gov/hostdata.rb, spec/identity/hostdata/config_builder_spec.rb, spec/identity/hostdata_spec.rb, spec/identity/login_gov/hostdata_spec.rb
This is an idea that's been floating around in my head for a bit, so I went for it. IDP PR coming soon as a demo
- Pull the `IdentityConfig` class we have copied into our various apps into the shared gem.
- Renames the old "config" (valuable short name) to host_config
=> Redo Identity::Hostdata.config

CHANGELOG.md, README.md, identity-hostdata.gemspec, lib/identity/hostdata/config_builder.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_builder_spec.rb, spec/identity/hostdata_spec.rb, spec/spec_helper.rb, spec/support/ec2_helpers.rb
Based on some upcoming data warehouse changes, we're going to store secrets in AWS Secrets Manager [(gitlab link)](https://gitlab.login.gov/lg/identity-devops/-/merge_requests/4533#note_174053)
This PR is an attempt to augment `Identity::Hostdata` config so that we can load those.
~Since SSM secrets have different name styles than our YML secrets, I opted for a new method, `add_ssm`.~
In this particular case, we have a JSON blob inside of the secret with two keys, so I added a block arg to let us process and yield out just the one value
=> Add method to load secrets from SecretsManager

spec/identity/hostdata/config_reader_spec.rb, spec/identity/hostdata/ec2_spec.rb, spec/support/ec2_helpers.rb
I added `EC2Helpers` in #40 out of necessity, this PR just follows up and update the rest of the test suite to use it.
=> Refactor EC2 in specs to use shared EC2Helpers module

identity-hostdata.gemspec, lib/identity/hostdata/config_builder.rb, lib/identity/hostdata/version.rb, spec/identity/hostdata/config_builder_spec.rb
Similar to #40, but with a slightly different approach. This PR is in draft status for now to help move towards something that can accommodate the multiple use cases we may have for secrets manager usage in applications.
=> Add Secrets Manager as a source for configuration values

.circleci/config.yml, identity-hostdata.gemspec
The current `rake` version specified is quite old (last version of 10.x was in January 2016) and is not compatible with newer versions of Ruby.
This PR updates both the Ruby version used in CI as well as the rake and bundler gems.
=> Update gems and CI Ruby version
